name: Wine Git CI Arm64

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04-arm

    steps:
      - uses: actions/checkout@v4

      - name: Download bootstraps artifact
        uses: dawidd6/action-download-artifact@v3
        with:
          workflow: bootstraps-arm.yml
          workflow_conclusion: success
          path: /opt

      - name: Prepare Environment and Build Wine
        run: |
          sudo apt update
          sudo apt install debootstrap perl git wget xz-utils bubblewrap autoconf
          sudo tar -C /opt -xpf /opt/Bootstraps/bootstraps.tar.xz
          chmod +x build_wine_arm64.sh
          export WINE_VERSION="$(wget -q -O - "https://raw.githubusercontent.com/Kron4ek/wine-tkg/master/VERSION" | tail -c +14)"
          echo "WINE_VERSION=${WINE_VERSION}" >> "$GITHUB_ENV"
          # export EXPERIMENTAL_WOW64="true"

          WINE_BRANCH=vanilla ./build_wine_arm64.sh
          # WINE_BRANCH=staging ./build_wine.sh
          sha256sum *.tar.xz

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Wine-Git
          path: ./*.tar.xz
